# Generated by Django 5.1.2 on 2025-11-10 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gen_settings', '0006_alter_empresa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaEquipo',
            fields=[
                ('marcaEquipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('marcaEquipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('tipoEquipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoEquipo', models.CharField(max_length=100)),
                ('siglaEquipo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('modeloEquipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('modeloEquipo', models.CharField(max_length=100)),
                ('marcaEquipo_id', models.ForeignKey(blank=True, db_column='marcaEquipo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='maquinarias.marcaequipo')),
                ('tipoEquipo_id', models.ForeignKey(blank=True, db_column='tipoEquipo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='maquinarias.tipoequipo')),
            ],
            options={
                'verbose_name': 'Modelo de Equipo',
                'verbose_name_plural': 'Modelos de Equipo',
                'unique_together': {('tipoEquipo_id', 'marcaEquipo_id', 'modeloEquipo')},
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('equipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigoInterno', models.CharField(max_length=100)),
                ('patente', models.CharField(blank=True, max_length=100, null=True)),
                ('horometro', models.IntegerField(default=0)),
                ('odometro', models.IntegerField(default=0)),
                ('horometroSuperEstructural', models.IntegerField(default=0)),
                ('nombreEquipo', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('empresa_id', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='gen_settings.empresa')),
                ('modeloEquipo_id', models.ForeignKey(db_column='modeloEquipo_id', on_delete=django.db.models.deletion.CASCADE, to='maquinarias.modeloequipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'unique_together': {('modeloEquipo_id', 'codigoInterno')},
            },
        ),
    ]
