# Generated by Django 5.1.2 on 2025-11-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='horometroSuperEstructural',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
