# Generated by Django 5.1.2 on 2025-11-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0002_alter_equipo_horometrosuperestructural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='horometro',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
