# Generated by Django 5.1.2 on 2025-11-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0003_alter_equipo_horometro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='horometro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='horometroSuperEstructural',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='odometro',
            field=models.IntegerField(),
        ),
    ]
