# Generated by Django 5.1.2 on 2025-11-11 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0004_alter_equipo_horometro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('seccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'maquinarias_seccion',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='equipo',
            name='odometro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PautaMantenimientoPreventivo',
            fields=[
                ('pauta_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('modeloEquipo_id', models.ForeignKey(db_column='modeloEquipo_id', on_delete=django.db.models.deletion.CASCADE, related_name='pautas_mantenimiento', to='maquinarias.modeloequipo')),
            ],
            options={
                'verbose_name': 'Pauta de Mantenimiento Preventivo',
                'verbose_name_plural': 'Pautas de Mantenimiento Preventivo',
                'db_table': 'maquinarias_pautamantenimientopreventivo',
                'ordering': ['modeloEquipo_id', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoReparacion',
            fields=[
                ('tipoReparacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('seccion_id', models.ForeignKey(db_column='seccion_id', on_delete=django.db.models.deletion.CASCADE, related_name='tipos_reparacion', to='maquinarias.seccion')),
            ],
            options={
                'verbose_name': 'Tipo de Reparación',
                'verbose_name_plural': 'Tipos de Reparación',
                'db_table': 'maquinarias_tiporeparacion',
                'ordering': ['seccion_id', 'nombre'],
                'unique_together': {('seccion_id', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ItemPauta',
            fields=[
                ('itemPauta_id', models.AutoField(primary_key=True, serialize=False)),
                ('pauta_id', models.ForeignKey(db_column='pauta_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maquinarias.pautamantenimientopreventivo')),
                ('seccion_id', models.ForeignKey(db_column='seccion_id', on_delete=django.db.models.deletion.CASCADE, related_name='items_pauta', to='maquinarias.seccion')),
                ('tipos_reparacion', models.ManyToManyField(related_name='items_pauta', to='maquinarias.tiporeparacion')),
            ],
            options={
                'verbose_name': 'Item de Pauta',
                'verbose_name_plural': 'Items de Pauta',
                'db_table': 'maquinarias_itempauta',
                'unique_together': {('pauta_id', 'seccion_id')},
            },
        ),
    ]
