# Generated by Django 5.1.2 on 2025-11-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0005_seccion_alter_equipo_odometro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tiporeparacion',
            name='activo',
        ),
    ]
