# Generated by Django 5.1.7 on 2025-11-13 23:45

import django.db.models.deletion
import maquinarias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0006_remove_seccion_activo_remove_tiporeparacion_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoMaquinaria',
            fields=[
                ('tipoDocumento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Documento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('requiere_fecha_vencimiento', models.BooleanField(default=False, help_text='Si está marcado, este tipo de documento requerirá una fecha de vencimiento al subirlo', verbose_name='Requiere Fecha de Vencimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Maquinaria',
                'verbose_name_plural': 'Tipos de Documentos de Maquinaria',
                'db_table': 'maquinarias_tipodocumento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumentoMaquinaria',
            fields=[
                ('historial_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento_nombre', models.CharField(help_text='Nombre del tipo de documento al momento de archivarlo', max_length=100, verbose_name='Tipo de Documento (Nombre)')),
                ('archivo', models.FileField(upload_to=maquinarias.models.obtener_ruta_documento_maquinaria, verbose_name='Archivo')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_subida_original', models.DateTimeField(blank=True, help_text='Fecha en que se subió originalmente este documento', null=True, verbose_name='Fecha de Subida Original')),
                ('fecha_reemplazo', models.DateTimeField(auto_now_add=True, help_text='Fecha en que este documento fue reemplazado', verbose_name='Fecha de Reemplazo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('equipo_id', models.ForeignKey(db_column='equipo_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial_documentos', to='maquinarias.equipo')),
                ('tipo_documento_id', models.ForeignKey(blank=True, db_column='tipo_documento_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='maquinarias.tipodocumentomaquinaria', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Historial de Documento de Maquinaria',
                'verbose_name_plural': 'Historial de Documentos de Maquinaria',
                'db_table': 'maquinarias_historialdocumento',
                'ordering': ['-fecha_reemplazo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoMaquinaria',
            fields=[
                ('documento_id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(storage=maquinarias.models.OverwriteStorage(), upload_to=maquinarias.models.obtener_ruta_documento_maquinaria, verbose_name='Archivo')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha en que vence el documento (si aplica)', null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('equipo_id', models.ForeignKey(db_column='equipo_id', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='maquinarias.equipo')),
                ('tipo_documento_id', models.ForeignKey(db_column='tipo_documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='maquinarias.tipodocumentomaquinaria', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento de Maquinaria',
                'verbose_name_plural': 'Documentos de Maquinaria',
                'db_table': 'maquinarias_documento',
                'ordering': ['tipo_documento_id__nombre'],
                'unique_together': {('equipo_id', 'tipo_documento_id')},
            },
        ),
    ]
