# Generated by Django 5.1.7 on 2025-11-14 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_settings', '0006_alter_empresa_options'),
        ('maquinarias', '0007_tipodocumentomaquinaria_historialdocumentomaquinaria_and_more'),
        ('rrhh_personal', '0024_ausentismo_dias_ausentismo_alter_ausentismo_fechafin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('ot_id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio')),
                ('horometro', models.IntegerField(blank=True, null=True, verbose_name='Horómetro')),
                ('odometro', models.IntegerField(blank=True, null=True, verbose_name='Odómetro')),
                ('horometro_superestructura', models.IntegerField(blank=True, null=True, verbose_name='Horómetro Superestructura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('corresponde_pauta', models.BooleanField(default=False, verbose_name='Corresponde a Pauta de Mantenimiento')),
                ('estado_ot', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('terminada', 'Terminada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado de la OT')),
                ('estado_equipo', models.CharField(choices=[('shutdown', 'Shutdown'), ('en_reparacion', 'En Reparación'), ('en_reparacion_disponible', 'En Reparación Disponible'), ('disponible', 'Disponible')], default='disponible', max_length=30, verbose_name='Estado del Equipo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('empresa_id', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='gen_settings.empresa', verbose_name='Empresa')),
                ('equipo_id', models.ForeignKey(db_column='equipo_id', on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='maquinarias.equipo', verbose_name='Equipo')),
                ('pauta_id', models.ForeignKey(blank=True, db_column='pauta_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='maquinarias.pautamantenimientopreventivo', verbose_name='Pauta de Mantenimiento')),
                ('personal_asignado', models.ManyToManyField(blank=True, related_name='ordenes_trabajo', to='rrhh_personal.personal', verbose_name='Personal Asignado')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Ordenes de Trabajo',
                'db_table': 'maquinarias_ordentrabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialObservacionesOT',
            fields=[
                ('historial_id', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_ot', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('ot_id', models.ForeignKey(db_column='ot_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial_observaciones', to='maquinarias.ordentrabajo', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Historial de Observación OT',
                'verbose_name_plural': 'Historial de Observaciones OT',
                'db_table': 'maquinarias_historialobservacionesot',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemSeccionOT',
            fields=[
                ('itemSeccionOT_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_seccion', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('terminada', 'Terminada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado de la Sección')),
                ('seccion_id', models.ForeignKey(db_column='seccion_id', on_delete=django.db.models.deletion.CASCADE, related_name='items_ot', to='maquinarias.seccion', verbose_name='Sección')),
                ('tipos_reparacion', models.ManyToManyField(related_name='items_ot', to='maquinarias.tiporeparacion', verbose_name='Tipos de Reparación')),
                ('ot_id', models.ForeignKey(db_column='ot_id', on_delete=django.db.models.deletion.CASCADE, related_name='items_secciones', to='maquinarias.ordentrabajo', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Item Sección OT',
                'verbose_name_plural': 'Items Secciones OT',
                'db_table': 'maquinarias_itemseccionot',
                'ordering': ['seccion_id__nombre'],
                'unique_together': {('ot_id', 'seccion_id')},
            },
        ),
    ]
