# Generated by Django 5.1.7 on 2025-11-14 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0008_ordentrabajo_historialobservacionesot_itemseccionot'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('estadoEquipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='secondary', max_length=20, verbose_name='Color (Bootstrap)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
            ],
            options={
                'verbose_name': 'Estado de Equipo',
                'verbose_name_plural': 'Estados de Equipo',
                'db_table': 'maquinarias_estadoequipo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoOT',
            fields=[
                ('estadoOT_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='secondary', max_length=20, verbose_name='Color (Bootstrap)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
            ],
            options={
                'verbose_name': 'Estado de OT',
                'verbose_name_plural': 'Estados de OT',
                'db_table': 'maquinarias_estadoot',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('tipoMantenimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimiento',
                'db_table': 'maquinarias_tipomantenimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='itemseccionot',
            name='estado_seccion',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='estado_equipo',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='estado_ot',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='tipo_mantenimiento',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado_equipo_id',
            field=models.ForeignKey(blank=True, db_column='estado_equipo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='maquinarias.estadoequipo', verbose_name='Estado del Equipo'),
        ),
        migrations.AddField(
            model_name='itempauta',
            name='estado_seccion_id',
            field=models.ForeignKey(blank=True, db_column='estado_seccion_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_pauta', to='maquinarias.estadoot', verbose_name='Estado de la Sección'),
        ),
        migrations.AddField(
            model_name='itemseccionot',
            name='estado_seccion_id',
            field=models.ForeignKey(blank=True, db_column='estado_seccion_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_secciones_ot', to='maquinarias.estadoot', verbose_name='Estado de la Sección'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado_ot_id',
            field=models.ForeignKey(blank=True, db_column='estado_ot_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='maquinarias.estadoot', verbose_name='Estado de la OT'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tipo_mantenimiento_id',
            field=models.ForeignKey(blank=True, db_column='tipo_mantenimiento_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='maquinarias.tipomantenimiento', verbose_name='Tipo de Mantenimiento'),
        ),
    ]
