# Generated by Django 5.1.7 on 2025-11-14 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0009_add_tipos_estados_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('accion', models.CharField(choices=[('OT_CREADA', 'OT Creada'), ('OT_MODIFICADA', 'OT Modificada'), ('ESTADO_OT_CAMBIADO', 'Estado OT Cambiado'), ('ESTADO_EQUIPO_CAMBIADO', 'Estado Equipo Cambiado'), ('ESTADO_SECCION_CAMBIADO', 'Estado Sección Cambiado'), ('FECHA_INICIO_CAMBIADA', 'Fecha Inicio Cambiada'), ('FECHA_FIN_CAMBIADA', 'Fecha Fin Cambiada'), ('PERSONAL_ASIGNADO', 'Personal Asignado'), ('PERSONAL_ELIMINADO', 'Personal Eliminado'), ('OBSERVACION_AGREGADA', 'Observación Agregada')], help_text='Tipo de acción realizada', max_length=50, verbose_name='Acción')),
                ('descripcion', models.TextField(help_text='Descripción detallada del cambio', verbose_name='Descripción')),
                ('datos_previos', models.JSONField(blank=True, help_text='Estado anterior antes del cambio (JSON)', null=True, verbose_name='Datos Previos')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado nuevo después del cambio (JSON)', null=True, verbose_name='Datos Nuevos')),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='maquinarias.ordentrabajo', verbose_name='Orden de Trabajo')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de OT',
                'verbose_name_plural': 'Historial de OTs',
                'db_table': 'maquinarias_historialot',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['ot', '-fecha_hora'], name='maquinarias_ot_id_6fdded_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='maquinarias_usuario_7906e6_idx')],
            },
        ),
    ]
