# Generated by Django 5.1.2 on 2025-11-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0010_historialot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempauta',
            name='estado_seccion_id',
        ),
    ]
