# Generated by Django 5.1.7 on 2025-11-15 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0011_remove_estado_seccion_from_itempauta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCalendarioEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('nombre_corto', models.CharField(blank=True, help_text="Nombre corto para mostrar en el calendario (ej: 'DISP' para 'Disponible')", max_length=10, null=True, verbose_name='Nombre Corto')),
                ('color', models.CharField(default='#000000', help_text='Color HEX para el texto del estado (ej: #0EA5E9)', max_length=7, verbose_name='Color Texto')),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Color HEX para el fondo del estado (ej: #0EA5E9)', max_length=7, verbose_name='Color Fondo')),
                ('prioridad', models.PositiveIntegerField(default=10, help_text='Mayor número => mayor prioridad si hay conflicto', verbose_name='Prioridad')),
                ('es_bloqueante', models.BooleanField(default=False, help_text='Si es True, este estado siempre sobreescribe cualquier otro que coincida', verbose_name='Es Bloqueante')),
                ('es_predeterminado', models.BooleanField(default=False, help_text='Si es True, este será el estado por defecto cuando no haya OT (Disponible)', verbose_name='Es Predeterminado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estado Calendario Equipo',
                'verbose_name_plural': 'Estados Calendario Equipo',
                'db_table': 'maquinarias_estadocalendarioequipo',
                'ordering': ['-activo', '-prioridad', 'nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('es_predeterminado', False), ('es_predeterminado', True), _connector='OR'), name='solo_un_estado_predeterminado_equipo')],
            },
        ),
        migrations.CreateModel(
            name='EstadoManualEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_manuales', to='maquinarias.equipo', verbose_name='Equipo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_manuales', to='maquinarias.estadocalendarioequipo', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado Manual Equipo',
                'verbose_name_plural': 'Estados Manuales Equipo',
                'db_table': 'maquinarias_estadomanualequipo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadoFuenteEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro_extra', models.JSONField(blank=True, null=True, verbose_name='Filtro Extra')),
                ('estado_calendario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuente', to='maquinarias.estadocalendarioequipo', verbose_name='Estado Calendario')),
                ('estado_equipo', models.ForeignKey(help_text='Estado de Equipo que se mapea a este estado del calendario', on_delete=django.db.models.deletion.CASCADE, related_name='fuentes_calendario', to='maquinarias.estadoequipo', verbose_name='Estado Equipo')),
            ],
            options={
                'verbose_name': 'Fuente de Estado Equipo',
                'verbose_name_plural': 'Fuentes de Estados Equipo',
                'db_table': 'maquinarias_estadofuenteequipo',
                'unique_together': {('estado_calendario', 'estado_equipo')},
            },
        ),
    ]
