# Generated by Django 5.1.2 on 2025-11-19 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0012_estadocalendarioequipo_estadomanualequipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('accion', models.CharField(choices=[('EQUIPO_CREADO', 'Equipo Creado'), ('EQUIPO_MODIFICADO', 'Equipo Modificado'), ('EQUIPO_ACTIVADO', 'Equipo Activado'), ('EQUIPO_DESACTIVADO', 'Equipo Desactivado'), ('EQUIPO_ELIMINADO', 'Equipo Eliminado'), ('ESTADO_MANUAL_ASIGNADO', 'Estado Manual Asignado'), ('ESTADO_MANUAL_MODIFICADO', 'Estado Manual Modificado'), ('ESTADO_MANUAL_ELIMINADO', 'Estado Manual Eliminado'), ('ASIGNACION_FAENA_CREADA', 'Asignación a Faena Creada'), ('ASIGNACION_FAENA_MODIFICADA', 'Asignación a Faena Modificada'), ('ASIGNACION_FAENA_ELIMINADA', 'Asignación a Faena Eliminada')], help_text='Tipo de acción realizada', max_length=50, verbose_name='Acción')),
                ('descripcion', models.TextField(help_text='Descripción detallada del cambio', verbose_name='Descripción')),
                ('datos_previos', models.JSONField(blank=True, help_text='Estado anterior antes del cambio (JSON)', null=True, verbose_name='Datos Previos')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado nuevo después del cambio (JSON)', null=True, verbose_name='Datos Nuevos')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='maquinarias.equipo', verbose_name='Equipo')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Equipo',
                'verbose_name_plural': 'Historial de Equipos',
                'db_table': 'maquinarias_historialequipo',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['equipo', '-fecha_hora'], name='maquinarias_equipo__f7e61d_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='maquinarias_usuario_cc1479_idx')],
            },
        ),
    ]
