# Generated by Django 5.1.7 on 2025-11-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0013_historialequipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentomaquinaria',
            options={'ordering': ['tipo_documento_id__nombre'], 'permissions': [('subir_documento', 'Puede subir documentos de maquinarias'), ('eliminar_documento', 'Puede eliminar documentos de maquinarias'), ('ver_historial_documentos', 'Puede ver historial de documentos')], 'verbose_name': 'Documento de Maquinaria', 'verbose_name_plural': 'Documentos de Maquinaria'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'permissions': [('desactivar_equipo', 'Puede desactivar equipos'), ('activar_equipo', 'Puede activar equipos'), ('exportar_equipos', 'Puede exportar datos de equipos'), ('ver_historial_equipo', 'Puede ver historial completo de equipos')], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('cambiar_estado_ot', 'Puede cambiar el estado de órdenes de trabajo'), ('asignar_personal_ot', 'Puede asignar personal a órdenes de trabajo'), ('agregar_observacion_ot', 'Puede agregar observaciones a órdenes de trabajo'), ('generar_pdf_ot', 'Puede generar PDF de órdenes de trabajo'), ('ver_historial_ot', 'Puede ver historial completo de órdenes de trabajo'), ('exportar_ots', 'Puede exportar datos de órdenes de trabajo')], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Ordenes de Trabajo'},
        ),
        migrations.AlterModelOptions(
            name='pautamantenimientopreventivo',
            options={'ordering': ['modeloEquipo_id', 'nombre'], 'permissions': [('desactivar_pauta', 'Puede desactivar pautas de mantenimiento'), ('activar_pauta', 'Puede activar pautas de mantenimiento'), ('exportar_pautas', 'Puede exportar datos de pautas de mantenimiento')], 'verbose_name': 'Pauta de Mantenimiento Preventivo', 'verbose_name_plural': 'Pautas de Mantenimiento Preventivo'},
        ),
    ]
