# Generated by Django 5.1.7 on 2025-11-30 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del permiso (ej: dashboards.view_dashboard_rrhh)', max_length=100, unique=True, verbose_name='Código del Permiso')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del permiso', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del permiso', verbose_name='Descripción')),
                ('app_label', models.CharField(help_text='Nombre de la app donde está la vista (ej: dashboards)', max_length=100, verbose_name='App')),
                ('vista_nombre', models.CharField(help_text='Nombre de la función/vista (ej: dashboard_rrhh)', max_length=200, verbose_name='Nombre de la Vista')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el permiso está activo', verbose_name='Activo')),
                ('permission', models.OneToOneField(blank=True, help_text='Permission de Django asociado (se crea automáticamente)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permiso_vista', to='auth.permission', verbose_name='Permission de Django')),
            ],
            options={
                'verbose_name': 'Permiso de Vista',
                'verbose_name_plural': 'Permisos de Vista',
                'ordering': ['app_label', 'vista_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único del rol (ej: Jefe de RRHH)', max_length=100, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del rol y sus responsabilidades', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el rol está activo y puede asignarse a usuarios', verbose_name='Activo')),
                ('permisos', models.ManyToManyField(blank=True, help_text='Permisos que tendrán todos los usuarios con este rol', to='auth.permission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion_rol', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se asignó el rol al usuario', verbose_name='Fecha de Asignación de Rol')),
                ('fecha_modificacion_rol', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación del rol del usuario', verbose_name='Fecha de Modificación de Rol')),
                ('rol', models.ForeignKey(blank=True, help_text='Rol asignado al usuario. Al asignar un rol, se asignan automáticamente todos sus permisos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gen_permissions.rol', verbose_name='Rol')),
                ('user', models.OneToOneField(help_text='Usuario asociado a este perfil', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='PermisoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del permiso (ej: rrhh_personal.desactivar_personal)', max_length=100, unique=True, verbose_name='Código del Permiso')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del permiso', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del permiso', verbose_name='Descripción')),
                ('accion', models.CharField(help_text='Nombre de la acción (ej: desactivar, activar, exportar)', max_length=100, verbose_name='Acción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el permiso está activo', verbose_name='Activo')),
                ('modelo', models.ForeignKey(help_text='Modelo al que pertenece este permiso de acción', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Modelo')),
                ('permission', models.OneToOneField(blank=True, help_text='Permission de Django asociado (se crea automáticamente)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permiso_accion', to='auth.permission', verbose_name='Permission de Django')),
            ],
            options={
                'verbose_name': 'Permiso de Acción',
                'verbose_name_plural': 'Permisos de Acción',
                'ordering': ['modelo', 'accion'],
                'unique_together': {('modelo', 'accion')},
            },
        ),
        migrations.CreateModel(
            name='PermisoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(help_text='Nombre de la app del modelo', max_length=100, verbose_name='App')),
                ('modelo_nombre', models.CharField(help_text='Nombre del modelo', max_length=100, verbose_name='Nombre del Modelo')),
                ('permisos_disponibles', models.JSONField(default=dict, help_text='Diccionario con los permisos disponibles para este modelo', verbose_name='Permisos Disponibles')),
                ('modelo', models.ForeignKey(help_text='Modelo al que pertenecen los permisos', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Permiso de Modelo',
                'verbose_name_plural': 'Permisos de Modelo',
                'unique_together': {('app_label', 'modelo_nombre')},
            },
        ),
    ]
