# Generated by Django 5.2.9 on 2025-12-14 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gen_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisoaccion',
            options={'ordering': ['modelo', 'accion'], 'verbose_name': 'Permiso de Accion', 'verbose_name_plural': 'Permisos de Accion'},
        ),
        migrations.AlterField(
            model_name='permisoaccion',
            name='accion',
            field=models.CharField(help_text='Nombre de la accion (ej: desactivar, activar, exportar)', max_length=100, verbose_name='Accion'),
        ),
        migrations.AlterField(
            model_name='permisoaccion',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el permiso esta activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='permisoaccion',
            name='codigo',
            field=models.CharField(help_text='Codigo unico del permiso (ej: rrhh_personal.desactivar_personal)', max_length=100, unique=True, verbose_name='Codigo del Permiso'),
        ),
        migrations.AlterField(
            model_name='permisoaccion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripcion detallada del permiso', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='permisoaccion',
            name='permission',
            field=models.OneToOneField(blank=True, help_text='Permission de Django asociado (se crea automaticamente)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permiso_accion', to='auth.permission', verbose_name='Permission de Django'),
        ),
        migrations.AlterField(
            model_name='permisovista',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el permiso esta activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='permisovista',
            name='app_label',
            field=models.CharField(help_text='Nombre de la app donde esta la vista (ej: dashboards)', max_length=100, verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='permisovista',
            name='codigo',
            field=models.CharField(help_text='Codigo unico del permiso (ej: dashboards.view_dashboard_rrhh)', max_length=100, unique=True, verbose_name='Codigo del Permiso'),
        ),
        migrations.AlterField(
            model_name='permisovista',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripcion detallada del permiso', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='permisovista',
            name='permission',
            field=models.OneToOneField(blank=True, help_text='Permission de Django asociado (se crea automaticamente)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permiso_vista', to='auth.permission', verbose_name='Permission de Django'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el rol esta activo y puede asignarse a usuarios', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripcion del rol y sus responsabilidades', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fecha_asignacion_rol',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en que se asigno el rol al usuario', verbose_name='Fecha de Asignacion de Rol'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fecha_modificacion_rol',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de ultima modificacion del rol del usuario', verbose_name='Fecha de Modificacion de Rol'),
        ),
    ]
