# Generated by Django 5.1.7 on 2025-10-18 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rrhh_personal', '0010_alter_licenciamedicaporpersonal_rutadoc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Faena',
                'verbose_name_plural': 'Faenas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_corto', models.CharField(blank=True, help_text="Nombre corto para mostrar en el calendario (ej: 'D' para 'Día', 'N' para 'Noche')", max_length=10, null=True)),
                ('color', models.CharField(help_text='Color HEX para el texto del estado (ej: #0EA5E9)', max_length=7)),
                ('background_color', models.CharField(help_text='Color HEX para el fondo del estado (ej: #0EA5E9)', max_length=7)),
                ('prioridad', models.PositiveIntegerField(default=10, help_text='Mayor número => mayor prioridad si hay conflicto')),
                ('es_bloqueante', models.BooleanField(default=False, help_text='Si es True, este estado siempre sobreescribe cualquier otro que coincida')),
                ('es_predeterminado', models.BooleanField(default=False, help_text='Si es True, este será el estado por defecto cuando no haya asignaciones')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['-activo', '-prioridad', 'nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('es_predeterminado', False), ('es_predeterminado', True), _connector='OR'), name='solo_un_estado_predeterminado')],
            },
        ),
        migrations.CreateModel(
            name='EstadoFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_fecha_inicio', models.CharField(default='fecha_inicio', max_length=50)),
                ('campo_fecha_fin', models.CharField(default='fecha_fin', max_length=50)),
                ('campo_personal', models.CharField(default='personal', max_length=50)),
                ('filtro_extra', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(help_text='Modelo origen (ej: Ausentismo, LicenciaMedica, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('estado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuente', to='ope_calendario.estado')),
            ],
            options={
                'verbose_name': 'Fuente de Estado',
                'verbose_name_plural': 'Fuentes de Estados',
            },
        ),
        migrations.CreateModel(
            name='TurnoBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Posición del bloque dentro del ciclo (1..n)')),
                ('duracion_dias', models.PositiveIntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_turno', to='ope_calendario.estado')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='ope_calendario.turno')),
            ],
            options={
                'verbose_name': 'Bloque de Turno',
                'verbose_name_plural': 'Bloques de Turno',
                'ordering': ['turno', 'orden'],
                'unique_together': {('turno', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='EstadoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(db_index=True)),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_manuales', to='ope_calendario.estado')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_manuales', to='rrhh_personal.personal')),
            ],
            options={
                'verbose_name': 'Estado Manual',
                'verbose_name_plural': 'Estados Manuales',
                'ordering': ['personal', 'fecha_inicio'],
                'indexes': [models.Index(fields=['personal', 'fecha_inicio', 'fecha_fin'], name='ope_calenda_persona_daa92a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='estado_manual_rango_valido')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionFaena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(blank=True, db_index=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_faena', to='rrhh_personal.personal')),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='ope_calendario.faena')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='ope_calendario.turno')),
                ('bloque_inicio', models.ForeignKey(help_text='Bloque del turno desde el cual arranca el ciclo para esta persona', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_inicio', to='ope_calendario.turnobloque')),
            ],
            options={
                'verbose_name': 'Asignación a Faena',
                'verbose_name_plural': 'Asignaciones a Faenas',
                'ordering': ['personal', 'fecha_inicio'],
                'indexes': [models.Index(fields=['personal', 'fecha_inicio', 'fecha_fin'], name='ope_calenda_persona_a06d4f_idx'), models.Index(fields=['faena', 'turno'], name='ope_calenda_faena_i_03be95_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio')), ('fecha_fin__isnull', True), _connector='OR'), name='asig_faena_rango_valido')],
            },
        ),
    ]
