# Generated by Django 5.1.2 on 2025-10-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ope_calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faena',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AddField(
            model_name='faena',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddConstraint(
            model_name='faena',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio')), ('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), _connector='OR'), name='faena_rango_valido'),
        ),
    ]
