# Generated by Django 5.1.7 on 2025-11-09 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ope_calendario', '0004_agregar_codigo_faena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faena',
            options={'ordering': ['codigo', 'nombre'], 'verbose_name': 'Faena', 'verbose_name_plural': 'Faenas'},
        ),
        migrations.AddField(
            model_name='estadomanual',
            name='faena',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='estados_manuales', to='ope_calendario.faena'),
        ),
    ]
