# Generated by Django 5.1.7 on 2025-11-09 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ope_calendario', '0005_alter_faena_options_estadomanual_faena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadomanual',
            name='faena',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_manuales', to='ope_calendario.faena'),
        ),
        migrations.AlterField(
            model_name='estadomanual',
            name='fecha_fin',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadomanual',
            name='fecha_inicio',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
