# Generated by Django 5.1.2 on 2025-11-12 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ope_calendario', '0006_alter_estadomanual_faena_and_more'),
        ('rrhh_personal', '0024_ausentismo_dias_ausentismo_alter_ausentismo_fechafin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialFaena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accion', models.CharField(choices=[('FAENA_CREADA', 'Faena Creada'), ('FAENA_MODIFICADA', 'Faena Modificada'), ('PERSONAL_ASIGNADO', 'Personal Asignado'), ('PERSONAL_ELIMINADO', 'Personal Eliminado'), ('ASIGNACION_MODIFICADA', 'Asignación Modificada'), ('TURNO_MODIFICADO', 'Turno Modificado'), ('FECHA_MODIFICADA', 'Fecha Modificada')], help_text='Tipo de acción realizada', max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción detallada del cambio')),
                ('datos_previos', models.JSONField(blank=True, help_text='Estado anterior antes del cambio (JSON)', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado nuevo después del cambio (JSON)', null=True)),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ope_calendario.faena')),
                ('personal', models.ForeignKey(blank=True, help_text='Personal involucrado en la acción (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_faenas', to='rrhh_personal.personal')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Faena',
                'verbose_name_plural': 'Historial de Faenas',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['faena', '-fecha_hora'], name='ope_calenda_faena_i_27ca89_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='ope_calenda_usuario_bec707_idx')],
            },
        ),
    ]
