# Generated by Django 5.1.2 on 2025-11-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinarias', '0012_estadocalendarioequipo_estadomanualequipo_and_more'),
        ('ope_calendario', '0007_historialfaena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialfaena',
            name='accion',
            field=models.CharField(choices=[('FAENA_CREADA', 'Faena Creada'), ('FAENA_MODIFICADA', 'Faena Modificada'), ('PERSONAL_ASIGNADO', 'Personal Asignado'), ('PERSONAL_ELIMINADO', 'Personal Eliminado'), ('ASIGNACION_MODIFICADA', 'Asignación Modificada'), ('TURNO_MODIFICADO', 'Turno Modificado'), ('FECHA_MODIFICADA', 'Fecha Modificada'), ('EQUIPO_ASIGNADO', 'Equipo Asignado'), ('EQUIPO_ELIMINADO', 'Equipo Eliminado')], help_text='Tipo de acción realizada', max_length=50),
        ),
        migrations.CreateModel(
            name='AsignacionEquipoFaena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(blank=True, db_index=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_faena', to='maquinarias.equipo')),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_equipos', to='ope_calendario.faena')),
            ],
            options={
                'verbose_name': 'Asignación de Equipo a Faena',
                'verbose_name_plural': 'Asignaciones de Equipos a Faenas',
                'ordering': ['equipo', 'fecha_inicio'],
                'indexes': [models.Index(fields=['equipo', 'fecha_inicio', 'fecha_fin'], name='ope_calenda_equipo__2ef152_idx'), models.Index(fields=['faena', 'fecha_inicio'], name='ope_calenda_faena_i_9c6eee_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio')), ('fecha_fin__isnull', True), _connector='OR'), name='asig_equipo_faena_rango_valido')],
            },
        ),
    ]
