# Generated by Django 5.1.2 on 2025-11-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ope_calendario', '0008_alter_historialfaena_accion_asignacionequipofaena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialfaena',
            name='accion',
            field=models.CharField(choices=[('FAENA_CREADA', 'Faena Creada'), ('FAENA_MODIFICADA', 'Faena Modificada'), ('PERSONAL_ASIGNADO', 'Personal Asignado'), ('PERSONAL_ELIMINADO', 'Personal Eliminado'), ('ASIGNACION_MODIFICADA', 'Asignación Modificada'), ('TURNO_MODIFICADO', 'Turno Modificado'), ('FECHA_MODIFICADA', 'Fecha Modificada'), ('EQUIPO_ASIGNADO', 'Equipo Asignado'), ('EQUIPO_ELIMINADO', 'Equipo Eliminado'), ('EQUIPO_MODIFICADO', 'Equipo Modificado')], help_text='Tipo de acción realizada', max_length=50),
        ),
    ]
