# Generated by Django 5.1.7 on 2025-11-30 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ope_calendario', '0009_alter_historialfaena_accion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionequipofaena',
            options={'ordering': ['equipo', 'fecha_inicio'], 'permissions': [('modificar_asignacion_equipo', 'Puede modificar asignaciones de equipos existentes')], 'verbose_name': 'Asignación de Equipo a Faena', 'verbose_name_plural': 'Asignaciones de Equipos a Faenas'},
        ),
        migrations.AlterModelOptions(
            name='asignacionfaena',
            options={'ordering': ['personal', 'fecha_inicio'], 'permissions': [('asignacion_masiva_personal', 'Puede realizar asignaciones masivas de personal'), ('modificar_asignacion_personal', 'Puede modificar asignaciones de personal existentes')], 'verbose_name': 'Asignación a Faena', 'verbose_name_plural': 'Asignaciones a Faenas'},
        ),
        migrations.AlterModelOptions(
            name='estadomanual',
            options={'ordering': ['personal', 'fecha_inicio'], 'permissions': [('asignar_estado_manual', 'Puede asignar estados manuales a personal'), ('eliminar_estado_manual', 'Puede eliminar estados manuales')], 'verbose_name': 'Estado Manual', 'verbose_name_plural': 'Estados Manuales'},
        ),
        migrations.AlterModelOptions(
            name='faena',
            options={'ordering': ['codigo', 'nombre'], 'permissions': [('desactivar_faena', 'Puede desactivar faenas'), ('activar_faena', 'Puede activar faenas'), ('asignar_personal_faena', 'Puede asignar personal a faenas'), ('asignar_equipos_faena', 'Puede asignar equipos a faenas'), ('ver_historial_faena', 'Puede ver historial completo de faenas'), ('exportar_faenas', 'Puede exportar datos de faenas')], 'verbose_name': 'Faena', 'verbose_name_plural': 'Faenas'},
        ),
    ]
