# Generated by Django 5.1.2 on 2025-12-04 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gen_permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del tipo de notificación (ej: RRHH_PERSONAL_ACTIVADO)', max_length=100, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tipo de notificación', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de cuándo se genera esta notificación', verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('RRHH', 'Recursos Humanos'), ('MAQUINARIAS', 'Maquinarias'), ('PLANIFICACION', 'Planificación'), ('GENERAL', 'General')], help_text='Categoría a la que pertenece esta notificación', max_length=20, verbose_name='Categoría')),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', help_text='Prioridad por defecto de las notificaciones de este tipo', max_length=10, verbose_name='Prioridad')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este tipo de notificación está activo y puede generar notificaciones', verbose_name='Activo')),
                ('template_titulo', models.CharField(blank=True, help_text='Template para el título (puede usar variables como {nombre}, {fecha})', max_length=200, verbose_name='Template de Título')),
                ('template_mensaje', models.TextField(blank=True, help_text='Template para el mensaje (puede usar variables como {nombre}, {fecha})', verbose_name='Template de Mensaje')),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificaciones',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(help_text='Mensaje completo de la notificación', verbose_name='Mensaje')),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON (IDs relacionados, URLs, etc.)', verbose_name='Datos Adicionales')),
                ('leida', models.BooleanField(default=False, help_text='Indica si el usuario ha leído esta notificación', verbose_name='Leída')),
                ('fecha_leida', models.DateTimeField(blank=True, help_text='Fecha y hora en que el usuario leyó la notificación', null=True, verbose_name='Fecha de Lectura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', help_text='Prioridad de la notificación', max_length=10, verbose_name='Prioridad')),
                ('archivada', models.BooleanField(default=False, help_text='Indica si la notificación ha sido archivada por el usuario', verbose_name='Archivada')),
                ('fecha_archivada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Archivado')),
                ('usuario', models.ForeignKey(help_text='Usuario destinatario de la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tipo_notificacion', models.ForeignKey(help_text='Tipo de notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='notificaciones.tiponotificacion', verbose_name='Tipo de Notificación')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida', '-fecha_creacion'], name='notificacio_usuario_73326f_idx'), models.Index(fields=['usuario', 'archivada', '-fecha_creacion'], name='notificacio_usuario_fc0d91_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificacionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este rol puede recibir notificaciones de este tipo', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('rol', models.ForeignKey(help_text='Rol al que se aplica esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_notificaciones', to='gen_permissions.rol', verbose_name='Rol')),
                ('tipo_notificacion', models.ForeignKey(help_text='Tipo de notificación que puede recibir este rol', on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_roles', to='notificaciones.tiponotificacion', verbose_name='Tipo de Notificación')),
            ],
            options={
                'verbose_name': 'Configuración de Notificación por Rol',
                'verbose_name_plural': 'Configuraciones de Notificaciones por Rol',
                'ordering': ['rol', 'tipo_notificacion'],
                'unique_together': {('rol', 'tipo_notificacion')},
            },
        ),
    ]
