# Generated by Django 5.1.3 on 2025-11-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
