# Generated by Django 5.1.2 on 2025-12-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VencimientoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Vencimiento de Documento',
                'verbose_name_plural': 'Vencimientos de Documentos',
                'permissions': [('view_vencimientos', 'Puede ver el panel de vencimientos de documentos')],
            },
        ),
    ]
