# Generated by Django 5.2.4 on 2025-07-24 15:46

import django.db.models.deletion
import rrhh_personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0005_alter_personal_certificado_afp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLicenciaMedica',
            fields=[
                ('tipoLicenciaMedica_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoLicenciaMedica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaMedicaPorPersonal',
            fields=[
                ('licenciaMedicaPorPersonal_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEmision', models.DateField()),
                ('dias_licencia', models.IntegerField()),
                ('rutaDoc', models.FileField(storage=rrhh_personal.models.OverwriteStorage, upload_to=rrhh_personal.models.obtener_ruta_documento)),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.personal')),
                ('tipos', models.ManyToManyField(related_name='licencias_medicas_personales', to='rrhh_personal.tipolicenciamedica')),
            ],
        ),
    ]
