# Generated by Django 5.2.4 on 2025-07-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0008_remove_licenciamedicaporpersonal_tipos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciamedicaporpersonal',
            name='tipoLicenciaMedica_id',
            field=models.ForeignKey(db_column='tipoLicenciaMedica_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipolicenciamedica'),
        ),
    ]
