# Generated by Django 5.1.7 on 2025-05-03 18:34

import django.db.models.deletion
import rrhh_personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gen_settings', '0005_alter_empresa_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseLicencia',
            fields=[
                ('claseLicencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('claseLicencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeptoEmpresa',
            fields=[
                ('depto_id', models.AutoField(primary_key=True, serialize=False)),
                ('depto', models.CharField(db_column='depto', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('estcivil_id', models.AutoField(primary_key=True, serialize=False)),
                ('estadocivil', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estadocivil',
            },
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('resultadoEx_id', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('sexo_id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sexo',
            },
        ),
        migrations.CreateModel(
            name='TipoAusentismo',
            fields=[
                ('tipoausen_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='tipo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCertificacion',
            fields=[
                ('tipoCertificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoCertificacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoClasificacion',
            fields=[
                ('tipoClasi_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('tipoEx_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoExamen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('tipoLicencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoLicencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(db_column='cargo', max_length=50)),
                ('depto_id', models.ForeignKey(db_column='depto_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.deptoempresa')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=8, unique=True)),
                ('dvrut', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('apepat', models.CharField(max_length=50)),
                ('apemat', models.CharField(max_length=50)),
                ('fechanac', models.DateField(blank=True, null=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('comuna_id', models.ForeignKey(blank=True, db_column='comuna_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_settings.comuna')),
                ('estcivil_id', models.ForeignKey(blank=True, db_column='estcivil_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.estadocivil')),
                ('region_id', models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='gen_settings.region')),
                ('sexo_id', models.ForeignKey(blank=True, db_column='sexo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.sexo')),
            ],
            options={
                'db_table': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='LicenciaPorPersonal',
            fields=[
                ('licenciaPorPersonal_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEmision', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('rutaDoc', models.FileField(storage=rrhh_personal.models.OverwriteStorage, upload_to=rrhh_personal.models.obtener_ruta_documento)),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('clases', models.ManyToManyField(related_name='licencias_personales', to='rrhh_personal.claselicencia')),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.personal')),
            ],
        ),
        migrations.CreateModel(
            name='InfoLaboral',
            fields=[
                ('infolab_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechacontrata', models.DateField()),
                ('cargo_id', models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.cargo')),
                ('depto_id', models.ForeignKey(db_column='depto_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.deptoempresa')),
                ('empresa_id', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='gen_settings.empresa')),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=8)),
                ('dvRut', models.CharField(max_length=1)),
                ('razonSocial', models.CharField(max_length=100)),
                ('nombreFant', models.CharField(blank=True, max_length=100, null=True)),
                ('giro', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna_id', models.ForeignKey(db_column='comuna_id', on_delete=django.db.models.deletion.CASCADE, to='gen_settings.comuna')),
                ('region_id', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.CASCADE, to='gen_settings.region')),
            ],
        ),
        migrations.CreateModel(
            name='Ausentismo',
            fields=[
                ('ausentismo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaini', models.DateField()),
                ('fechafin', models.DateField()),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.personal')),
                ('tipoausen_id', models.ForeignKey(db_column='tipoausen_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipoausentismo')),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('certif_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEmision', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('rutaDoc', models.FileField(upload_to=rrhh_personal.models.obtener_ruta_documento)),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.personal')),
                ('proveedor_id', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.proveedor')),
                ('tipoCertificacion_id', models.ForeignKey(db_column='tipoCertificacion_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipocertificacion')),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionProveedor',
            fields=[
                ('clasifProv_id', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor_id', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.proveedor')),
                ('tipoClasi_id', models.ForeignKey(db_column='tipoClasi_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipoclasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('examen_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEmision', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('rutaDoc', models.FileField(upload_to=rrhh_personal.models.obtener_ruta_documento)),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.personal')),
                ('proveedor_id', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.proveedor')),
                ('resultadoEx_id', models.ForeignKey(db_column='resultadoEx_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.resultadoexamen')),
                ('tipoEx_id', models.ForeignKey(db_column='tipoEx_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipoexamen')),
            ],
        ),
        migrations.AddField(
            model_name='claselicencia',
            name='tipoLicencia_id',
            field=models.ForeignKey(db_column='tipoLicencia_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipolicencia'),
        ),
    ]
