# Generated by Django 5.1.7 on 2025-05-10 19:11

import rrhh_personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0002_personal_certificado_afp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='comprobante_banco',
            field=models.FileField(blank=True, null=True, upload_to=rrhh_personal.models.obtener_ruta_documento_personal, verbose_name='Formulario de Depósito Bancario'),
        ),
    ]
