# Generated by Django 5.1.7 on 2025-05-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0003_personal_activo_alter_personal_comprobante_banco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciaporpersonal',
            name='clases',
        ),
        migrations.AddField(
            model_name='licenciaporpersonal',
            name='tipos',
            field=models.ManyToManyField(related_name='licencias_personales', to='rrhh_personal.tipolicencia'),
        ),
        migrations.DeleteModel(
            name='ClaseLicencia',
        ),
    ]
