# Generated by Django 5.2.4 on 2025-07-24 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0006_tipolicenciamedica_licenciamedicaporpersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciamedicaporpersonal',
            name='fecha_fin_licencia',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='licenciamedicaporpersonal',
            name='numero_folio',
            field=models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='N° Folio'),
        ),
    ]
