# Generated by Django 5.2.4 on 2025-07-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0007_licenciamedicaporpersonal_fecha_fin_licencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciamedicaporpersonal',
            name='tipos',
        ),
        migrations.AddField(
            model_name='licenciamedicaporpersonal',
            name='tipoLicenciaMedica_id',
            field=models.ForeignKey(blank=True, db_column='tipoLicenciaMedica_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipolicenciamedica'),
        ),
    ]
