# Generated by Django 5.1.7 on 2025-10-18 17:55

import rrhh_personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0009_alter_licenciamedicaporpersonal_tipolicenciamedica_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciamedicaporpersonal',
            name='rutaDoc',
            field=models.FileField(storage=rrhh_personal.models.OverwriteStorage(), upload_to=rrhh_personal.models.obtener_ruta_documento),
        ),
        migrations.AlterField(
            model_name='licenciaporpersonal',
            name='rutaDoc',
            field=models.FileField(storage=rrhh_personal.models.OverwriteStorage(), upload_to=rrhh_personal.models.obtener_ruta_documento),
        ),
    ]
