# Generated by Django 5.1.7 on 2025-10-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0010_alter_licenciamedicaporpersonal_rutadoc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipolicencia',
            options={'ordering': ['es_interna', 'tipoLicencia']},
        ),
        migrations.AddField(
            model_name='tipolicencia',
            name='es_interna',
            field=models.BooleanField(default=False, verbose_name='Licencia Interna'),
        ),
        migrations.AlterModelTable(
            name='tipolicencia',
            table='tipolicencia',
        ),
    ]
