# Generated by Django 5.1.7 on 2025-10-18 23:21

import django.db.models.deletion
import rrhh_personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0011_alter_tipolicencia_options_tipolicencia_es_interna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLicenciaInterna',
            fields=[
                ('tipoLicenciaInterna_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoLicenciaInterna', models.CharField(max_length=100, verbose_name='Tipo de Licencia Interna')),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Licencia Interna',
                'verbose_name_plural': 'Tipos de Licencias Internas',
                'db_table': 'tipo_licencia_interna',
                'ordering': ['tipoLicenciaInterna'],
            },
        ),
        migrations.AlterModelOptions(
            name='tipolicencia',
            options={},
        ),
        migrations.RemoveField(
            model_name='tipolicencia',
            name='es_interna',
        ),
        migrations.AlterModelTable(
            name='tipolicencia',
            table=None,
        ),
        migrations.CreateModel(
            name='LicenciaInternaPorPersonal',
            fields=[
                ('licenciaInterna_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_licencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de Licencia Interna')),
                ('fechaEmision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fechaVencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('empresa_emisora', models.CharField(blank=True, help_text='Empresa o faena que emitió la licencia interna', max_length=100, null=True, verbose_name='Empresa/Faena Emisora')),
                ('rutaDoc', models.FileField(blank=True, null=True, storage=rrhh_personal.models.OverwriteStorage(), upload_to=rrhh_personal.models.obtener_ruta_documento, verbose_name='Documento')),
                ('observacion', models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, related_name='licencias_internas', to='rrhh_personal.personal')),
                ('tipos', models.ManyToManyField(related_name='licencias_internas_personales', to='rrhh_personal.tipolicenciainterna', verbose_name='Tipos de Licencia Interna')),
            ],
            options={
                'verbose_name': 'Licencia Interna de Conducir',
                'verbose_name_plural': 'Licencias Internas de Conducir',
                'db_table': 'licencia_interna_por_personal',
                'ordering': ['-fechaEmision'],
            },
        ),
    ]
