# Generated by Django 5.1.7 on 2025-10-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0012_tipolicenciainterna_alter_tipolicencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='fecha_vencimiento_carnet',
            field=models.DateField(blank=True, help_text='Fecha en que vence el carnet de identidad', null=True, verbose_name='Fecha de Vencimiento del Carnet'),
        ),
    ]
