# Generated by Django 5.1.2 on 2025-10-23 17:48

import rrhh_personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0017_datos_iniciales_completos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciainternaporpersonal',
            name='rutaDoc',
            field=models.FileField(default=None, storage=rrhh_personal.models.OverwriteStorage(), upload_to=rrhh_personal.models.obtener_ruta_documento, verbose_name='Documento'),
        ),
    ]
