# Generated by Django 5.1.7 on 2025-11-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0018_alter_licenciainternaporpersonal_rutadoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fecha_vencimiento_carnet',
            field=models.DateField(default='2030-12-31', help_text='Fecha en que vence el carnet de identidad', verbose_name='Fecha de Vencimiento del Carnet'),
        ),
    ]
