# Generated by Django 5.1.7 on 2025-11-05 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0019_alter_personal_fecha_vencimiento_carnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fecha_vencimiento_carnet',
            field=models.DateField(default=datetime.date.today, help_text='Fecha en que vence el carnet de identidad', verbose_name='Fecha de Vencimiento del Carnet'),
        ),
    ]
