# Generated by Django 5.1.7 on 2025-11-05 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0021_alter_personal_fecha_vencimiento_carnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciainternaporpersonal',
            name='activo',
        ),
    ]
