# Generated by Django 5.1.7 on 2025-11-05 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0022_remove_licenciainternaporpersonal_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenciamedicaporpersonal',
            options={'ordering': ['-fechaEmision'], 'verbose_name': 'Licencia Médica', 'verbose_name_plural': 'Licencias Médicas'},
        ),
        migrations.RemoveField(
            model_name='licenciamedicaporpersonal',
            name='numero_folio',
        ),
        migrations.RemoveField(
            model_name='licenciamedicaporpersonal',
            name='rutaDoc',
        ),
        migrations.AlterField(
            model_name='licenciamedicaporpersonal',
            name='dias_licencia',
            field=models.IntegerField(verbose_name='Días de Licencia'),
        ),
        migrations.AlterField(
            model_name='licenciamedicaporpersonal',
            name='fechaEmision',
            field=models.DateField(verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='licenciamedicaporpersonal',
            name='fecha_fin_licencia',
            field=models.DateField(default=datetime.datetime.now, editable=False, verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='licenciamedicaporpersonal',
            name='observacion',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterModelTable(
            name='licenciamedicaporpersonal',
            table='licencia_medica_por_personal',
        ),
    ]
