# Generated by Django 5.1.7 on 2025-11-09 14:55

from django.db import migrations, models


def calcular_dias_ausentismo(apps, schema_editor):
    """
    Calcula el campo dias_ausentismo para registros existentes
    basándose en la diferencia entre fechafin y fechaini
    """
    Ausentismo = apps.get_model('rrhh_personal', 'Ausentismo')
    for ausentismo in Ausentismo.objects.all():
        if ausentismo.fechaini and ausentismo.fechafin:
            # Calcular días: (fechafin - fechaini) + 1 (porque incluye ambos días)
            dias = (ausentismo.fechafin - ausentismo.fechaini).days + 1
            ausentismo.dias_ausentismo = max(dias, 1)  # Al menos 1 día
            ausentismo.save()


def reverse_calcular_dias(apps, schema_editor):
    """No necesitamos hacer nada al revertir"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0023_alter_licenciamedicaporpersonal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausentismo',
            name='dias_ausentismo',
            field=models.IntegerField(default=1, verbose_name='Días de Ausentismo'),
        ),
        migrations.RunPython(calcular_dias_ausentismo, reverse_calcular_dias),
        migrations.AlterField(
            model_name='ausentismo',
            name='fechafin',
            field=models.DateField(editable=False, verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='fechaini',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='ausentismo',
            name='observacion',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones'),
        ),
    ]
