# Generated by Django 5.1.2 on 2025-11-19 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0024_ausentismo_dias_ausentismo_alter_ausentismo_fechafin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDocumentoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('tipo_documento', models.CharField(choices=[('DOCUMENTO_PERSONAL', 'Documento Personal'), ('LICENCIA_CONDUCIR', 'Licencia de Conducir'), ('LICENCIA_INTERNA', 'Licencia Interna'), ('LICENCIA_MEDICA', 'Licencia Médica'), ('CERTIFICACION', 'Certificación'), ('EXAMEN', 'Examen')], help_text='Tipo de documento afectado', max_length=50, verbose_name='Tipo de Documento')),
                ('accion', models.CharField(choices=[('DOCUMENTO_AGREGADO', 'Documento Agregado'), ('DOCUMENTO_MODIFICADO', 'Documento Modificado'), ('DOCUMENTO_ELIMINADO', 'Documento Eliminado'), ('DOCUMENTO_REEMPLAZADO', 'Documento Reemplazado')], help_text='Tipo de acción realizada', max_length=50, verbose_name='Acción')),
                ('nombre_documento', models.CharField(help_text='Nombre o descripción del documento', max_length=255, verbose_name='Nombre del Documento')),
                ('campo_documento', models.CharField(blank=True, help_text='Campo del modelo donde se almacena (si aplica)', max_length=100, null=True, verbose_name='Campo del Documento')),
                ('archivo_ruta', models.CharField(blank=True, help_text='Ruta del archivo (si fue eliminado, se guarda la ruta anterior)', max_length=500, null=True, verbose_name='Ruta del Archivo')),
                ('descripcion', models.TextField(help_text='Descripción detallada del cambio', verbose_name='Descripción')),
                ('datos_previos', models.JSONField(blank=True, help_text='Estado anterior antes del cambio (JSON)', null=True, verbose_name='Datos Previos')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado nuevo después del cambio (JSON)', null=True, verbose_name='Datos Nuevos')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_documentos', to='rrhh_personal.personal', verbose_name='Personal')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Documento de Personal',
                'verbose_name_plural': 'Historial de Documentos de Personal',
                'db_table': 'rrhh_personal_historialdocumentopersonal',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['personal', '-fecha_hora'], name='rrhh_person_persona_b071b9_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='rrhh_person_usuario_ad1a95_idx'), models.Index(fields=['tipo_documento', '-fecha_hora'], name='rrhh_person_tipo_do_b2b3e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('accion', models.CharField(choices=[('PERSONAL_CREADO', 'Personal Creado'), ('PERSONAL_MODIFICADO', 'Personal Modificado'), ('PERSONAL_ACTIVADO', 'Personal Activado'), ('PERSONAL_DESACTIVADO', 'Personal Desactivado'), ('PERSONAL_ELIMINADO', 'Personal Eliminado')], help_text='Tipo de acción realizada', max_length=50, verbose_name='Acción')),
                ('descripcion', models.TextField(help_text='Descripción detallada del cambio', verbose_name='Descripción')),
                ('datos_previos', models.JSONField(blank=True, help_text='Estado anterior antes del cambio (JSON)', null=True, verbose_name='Datos Previos')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado nuevo después del cambio (JSON)', null=True, verbose_name='Datos Nuevos')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='rrhh_personal.personal', verbose_name='Personal')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Personal',
                'verbose_name_plural': 'Historial de Personal',
                'db_table': 'rrhh_personal_historialpersonal',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['personal', '-fecha_hora'], name='rrhh_person_persona_84ee77_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='rrhh_person_usuario_e5f561_idx')],
            },
        ),
    ]
