# Generated by Django 5.1.7 on 2025-11-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0025_historialdocumentopersonal_historialpersonal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'permissions': [('desactivar_personal', 'Puede desactivar personal'), ('activar_personal', 'Puede activar personal'), ('exportar_personal', 'Puede exportar datos de personal'), ('ver_salarios', 'Puede ver información salarial')]},
        ),
    ]
