# Generated by Django 5.1.7 on 2025-11-30 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0026_alter_personal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'permissions': [('desactivar_personal', 'Puede desactivar personal'), ('activar_personal', 'Puede activar personal'), ('exportar_personal', 'Puede exportar datos de personal'), ('ver_salarios', 'Puede ver información salarial'), ('ver_historial_personal', 'Puede ver historial completo de personal')]},
        ),
    ]
