# Generated by Django 5.2 on 2025-04-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_settings', '0003_alter_unidadmedida_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
