# Generated by Django 5.1.7 on 2025-05-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gen_settings', '0005_alter_empresa_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
