# Generated by Django 5.2 on 2025-04-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gen_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
    ]
